openapi: 3.0.3
info:
  title: 安全管理平台中心端接口文档
  description: "# \U0001F3C1 变更记录\n\n图例：\n\n✨：`新增接口`\n\n✏️：`修改接口`\n\n\U0001F5D1️：`删除接口`\n\n# \U0001F91D 规则约定\n\n## 错误码\n\n可以通过 HTTP 状态码来判断也出是否处理成功：\n\n- `2xx`：代表后端业务处理成功。\n\n- `4xx`：代表客户端错误，请根据提示检查请求信息。\n\n- `401`：在本系统中有特殊含义，代表 `用户认证无效`，前端页码应该重定向至登录页让用户重新登录。\n\n- `5xx`：代表后端服务有问题，应联系后端开发进行修复。\n\n> - `2xx`：状态码代表业务处理成功，此时 Body 中不会包含二级业务状态码，直接取 Body 就是返回的信息。（有些业务可能 Body 为空，比如创建用户，提交后创建成功则无需返回什么内容，要视情况而定）。\n>\n> - `4xx` `5xx`：代表处理异常。具体是什么问题，请读取 Body 解析。Body 格式大致遵循 [RFC 7807](https://www.ietf.org/rfc/rfc7807.html) Problem Details。对于一些未先预料的业务错误，响应的 Body 不是 JSON 的，前端也应该做兜底处理，给用户一个友好提示。 \n\n## 认证信息\n\n在 [用户登录](operations/post-login) 认证成功后，返回报文中会有一个 `token` 字段，在调用需要登录认证的接口时，请在 Request Header 的 `Authorization` 中携带上 `token`。\n\n> - 对于一些不方便设置 Header `Authorization` 的请求，如：`websocket`、 `sse` 或调用浏览器下载 `windows.open()` 等操作，也可以将 Token 带到 query 参数中，如：`authorization=token` （注意在 query 参数中 `authorization` 是纯小写）。query 携带 Token 仅支持 `GET` 方法，其他方法带了 query Token 后端也不会处理。\n>\n> - 对于 `GET` 方法，推荐将 Token 带到 Header 中，query 参数只是为了照顾不方便设置 Header 的请求而使用的。如果 `GET` 方法同时设置了 Header 和 query Token，则以 Header 中的 Token 为准。\n>\n> - 该 Token 只是代表用户唯一且有效的普通字符串，并非 [JWT](https://www.ietf.org/rfc/rfc7519.html) Token。\n>\n> - 目前用户不可重复登录，当用户在其他地方登陆成功后，之前签发的 Token 会立即失效。\n>\n> - 该 Token 在后端会类似于 session 续期，如果用户一直的操作交互，则该 Token 会一直续期一直有效。\n\n## 时间格式\n\n时间格式使用 [RFC 3339](https://www.ietf.org/rfc/rfc3339.html)，若有特殊情况使用其他格式，则会在字段处单独说明。\n\n### js 解析 RFC 3339\n```javascript\nlet str = \"2023-03-30T02:59:41.679Z\";\nlet date = new Date(str); // Date 构造方法就可以解析 RFC3339 格式的时间\n```\n\n### js 生成 RFC 3339 格式字符串\n```javascript\nlet now = new Date();\nnow.toJSON(); // 2023-03-30T02:59:41.679Z\n\nlet obj = {timeAt: now};\nJSON.stringify(obj); // {\"timeAt\":\"2023-03-30T02:59:41.679Z\"}\n\n```"
  version: 0.0.1
  contact:
    name: 东方财富安全团队
    url: 'https://security.eastmoney.com'
    email: none@none.none
  termsOfService: 'https://security.eastmoney.com'
  x-logo:
    url: logo.ico
servers:
  - url: /api/v1
    description: 中心端
tags:
  - name: 登录模块
    description: 用户登录用到的接口
  - name: Agent
    description: Agent 节点模块
  - name: 用户模块
    description: 对系统用户管理
  - name: 用户日志
    description: 用户操作访问日志
  - name: 节点调用
    description: 对节点直接操作
  - name: 插件配置
    description: substance lua 脚本
  - name: 配置参数
    description: 配置参数
paths:
  /login/han:
    post:
      summary: 获取汉字点选验证码
      operationId: post-login-han
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  han_id:
                    type: string
                    description: 图片验证码唯一 ID
                  large:
                    type: string
                    description: 大图 base64
                  small:
                    type: string
                    description: 小图 base64
              examples:
                Example 1:
                  value:
                    han_id: cbd22fa9b421c0f3c0def9524ebbb284
                    large: 'data:image/jpeg;base64,/9j/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBoeVbzQwsxUiKaAKuwkAkPufbjaGJYAFjWMowxEpYPEUVVw+Kozo1Iy0Uqc1aUW1rtflts7PzOilUjHEUZOXxX5l3v37+jPUP2rfB2nQ+ItD+Mvg5XuPBPxks01gFkTyNF8UPbRT3mnXAiHlmS6i2qhYeZJfR3TEl95r5cguZY0xDIRHMhjUFju8vezKj85IwRweMk8Ak5+6/hOuj/ABSNSElKKZ4WIrudCVOaVSElyyjJXjJO++qavumrSi7OLwH/2Q=='
                    small: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAAAoBAMAAADu7x7UAAAAJ1BMVEUAAAAAZgAAXbmqACqHVABuNwHOWIhYZ6aOhEITgrBCMdd9sMY8ugvakvGtMcIed0HL/s+/nU/aOljvG9pE708KAvGDXf1N0mLp34SI+C5VO5qWnwEAAP//onRgJv6mIg8AAAAASUVORK5CYII='
        '400':
          $ref: '#/components/responses/ProblemDetails'
      description: 获取汉字点选验证码
      tags:
        - 登录模块
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 用户名
                password:
                  type: string
                  format: password
                  description: 密码
              required:
                - username
                - password
    put:
      summary: 校验汉字点选验证码
      operationId: put-login-han
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  dong:
                    type: boolean
                    description: 是否需要咚咚验证码
              examples:
                Example 1:
                  value:
                    dong: true
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 登录模块
      description: '每个汉字点选图片验证码只可以使用 `1` 次，无论点选结果是否验证成功，都不可以二次提交验证。如果验证错误，前端界面请自行请求 [获取汉字点选验证码](post-login-han) 获取新的图片验证码。'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
                  points:
                    - x: 12
                      'y': 345
                    - x: 234
                      'y': 127
                    - x: 654
                      'y': 222
              properties:
                username:
                  type: string
                  example: '123321'
                  minLength: 1
                  maxLength: 20
                  description: 用户名
                password:
                  type: string
                  description: 密码
                  format: password
                  example: p@33w0Rd
                  minLength: 6
                  maxLength: 32
                han_id:
                  type: string
                  description: 图片验证码的唯一 ID
                  example: cbd22fa9b421c0f3c0def9524ebbb284
                points:
                  type: array
                  description: 点选坐标信息
                  items:
                    type: object
                    properties:
                      x:
                        type: integer
                        minimum: 0
                        example: 321
                        description: X 轴
                      'y':
                        type: integer
                        minimum: 0
                        example: 214
                        description: Y 轴
                    required:
                      - x
                      - 'y'
              required:
                - username
                - password
                - han_id
                - points
            examples:
              Example 1:
                value:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
                  points:
                    - x: 12
                      'y': 345
                    - x: 234
                      'y': 127
                    - x: 654
                      'y': 222
      security: []
  /login/dong:
    post:
      summary: 获取咚咚验证码
      operationId: post-login-dong
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 登录模块
      description: '当 [校验汉字点选验证码](put-login-han) 验证码验证通过后，且返回的字段 `dong` 是 `true` 的时候，说明用户登录需要接收咚咚验证码。调用该接口后该用户的咚咚将会收到一条咚咚登录验证码，一般为 `6 位数字`。'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
              properties:
                username:
                  type: string
                  description: 用户名
                  minLength: 1
                  maxLength: 20
                  example: '123321'
                password:
                  type: string
                  description: 密码
                  format: password
                  example: p@33w0Rd
                  minLength: 6
                  maxLength: 32
                han_id:
                  type: string
                  description: 已经校验成功的图片验证码唯一 ID
                  maxLength: 100
                  minLength: 1
                  example: cbd22fa9b421c0f3c0def9524ebbb284
              required:
                - username
                - password
                - han_id
            examples:
              Example 1:
                value:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
      security: []
  /login:
    post:
      summary: 用户登录
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: '28522648801820918'
                    username: '123321'
                    nickname: 李小四
                    token: '28522648801820918'
                    issued_at: '2023-03-30T05:30:01.497Z'
                    lasted_at: '2023-03-30T05:30:01.497Z'
                properties:
                  id:
                    type: string
                    description: 用户 ID
                  username:
                    type: string
                    description: 用户名（用户登录名）
                  nickname:
                    type: string
                    description: 用户昵称
                  token:
                    type: string
                    description: 签发的 Token
                  issued_at:
                    type: string
                    description: 签发时间（当前登录时间）
                  lasted_at:
                    type: string
                    description: session 最近一次活动时间（当前登录时间）
              examples:
                Example 1:
                  value:
                    id: '28522648801820918'
                    username: '123321'
                    nickname: 李小四
                    token: 28522648801320969.crdix0mnpac0.38141bcbc37cfbff98d470b0b969b6c8bc70ccd56d0b3105832673976342b48f
                    issued_at: '2023-03-30T05:30:01.497Z'
                    lasted_at: '2023-03-30T05:30:01.497Z'
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 登录模块
      description: '当 [校验汉字点选验证码](put-login-han) 验证通过后，且 [获取咚咚验证码](post-login-dong) 已经填写（如果需要咚咚验证码的话），则可以调用该接口进行登录操作。'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
                  dong: '186618'
              properties:
                username:
                  type: string
                  description: 用户名
                  minLength: 1
                  maxLength: 20
                  example: '123321'
                password:
                  type: string
                  description: 密码
                  format: password
                  minLength: 6
                  maxLength: 32
                  example: p@33w0Rd
                han_id:
                  type: string
                  description: 图片验证码 ID
                  minLength: 1
                  maxLength: 100
                  example: cbd22fa9b421c0f3c0def9524ebbb284
                dong:
                  type: string
                  description: 咚咚收到的验证码（如果有的话）
              required:
                - username
                - password
                - han_id
            examples:
              Example 1:
                value:
                  username: '123321'
                  password: p@33w0Rd
                  han_id: cbd22fa9b421c0f3c0def9524ebbb284
                  dong: '186618'
      security: []
  /logout:
    delete:
      summary: 用户退出登录
      operationId: delete-logout
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 登录模块
      description: 用户退出登录
  /minions:
    get:
      summary: 查看节点列表
      tags:
        - Agent
      responses:
        '200':
          description: OK
      operationId: get-minions
      description: 查看节点列表
      parameters:
        - $ref: '#/components/parameters/PageCurrent'
        - $ref: '#/components/parameters/PageSize'
  /minion:
    get:
      summary: 查看节点详情
      tags:
        - Agent
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-minion
      description: 查看节点详情
      parameters:
        - $ref: '#/components/parameters/ID'
    post:
      summary: 添加节点
      operationId: post-minion
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - Agent
      description: 添加节点
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                inet:
                  type: string
                  description: 节点 IPv4
                  format: ipv4
                  default: 192.168.1.2
                  example: 192.168.1.2
                goos:
                  type: string
                  description: 节点操作系统
                  enum:
                    - linux
                    - windows
                    - darwin
                    - android
                  example: linux
                arch:
                  type: string
                  description: 节点架构
                  enum:
                    - amd64
                    - '386'
                    - arm64
                    - arm
                  example: amd64
              required:
                - inet
            examples:
              Example 1:
                value:
                  inet: 192.168.1.2
                  goos: linux
                  arch: amd64
  /users:
    get:
      summary: 用户列表查询
      tags:
        - 用户模块
      operationId: get-users
      description: 用户列表查询
      parameters:
        - $ref: '#/components/parameters/PageCurrent'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
  /user:
    post:
      summary: 添加用户
      operationId: post-user
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 用户模块
      description: |
        ## 账户类型（domain 字段）

        - `1`：本地账户，本地账户 `password` 必须填写。

        - `2`：OSS 认证账户，`password` 无需填写。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  username: '123321'
                  nickname: 田丽丽
                  domain: 1
                  password: p@33W0Rd
                  enable: true
              properties:
                username:
                  type: string
                  minLength: 1
                  maxLength: 20
                  example: '123321'
                  description: 用户名
                  default: '123321'
                nickname:
                  type: string
                  example: 曲丽丽
                  default: 曲丽丽
                  minLength: 1
                  maxLength: 20
                  description: 密码
                domain:
                  type: integer
                  enum:
                    - 1
                    - 2
                  example: 1
                  description: 账户类型
                password:
                  description: 用户密码（当本地用户时必须填写）
                  type: string
                enable:
                  type: boolean
                  description: 是否启用该用户
              required:
                - username
                - nickname
                - domain
            examples:
              添加本地账户:
                value:
                  username: '123321'
                  nickname: 曲丽丽
                  domain: 1
                  password: p@33W0Rd
                  enable: true
              添加 OSS 账户（OA 认证）:
                value:
                  username: '123321'
                  nickname: 田丽丽
                  domain: 2
                  enable: true
    delete:
      summary: 删除用户
      operationId: delete-user
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 用户模块
      description: 根据 `用户 ID` 删除用户
      parameters:
        - $ref: '#/components/parameters/UserID'
  /user/info:
    get:
      summary: 获取 session
      tags:
        - 用户模块
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: '28522648801820918'
                    username: '123321'
                    nickname: 李小四
                    token: 28522648801320969.crdix0mnpac0.38141bcbc37cfbff98d470b0b969b6c8bc70ccd56d0b3105832673976342b48f
                    issued_at: '2023-03-30T05:30:01.497Z'
                    lasted_at: '2023-03-30T07:12:11.125Z'
                properties:
                  id:
                    type: string
                    description: 用户 ID
                  username:
                    type: string
                    description: 用户名
                  nickname:
                    type: string
                    description: 用户昵称
                  token:
                    type: string
                    description: 用户 Token
                  issued_at:
                    type: string
                    description: Token 签发时间
                  lasted_at:
                    type: string
                    description: 最近一次活动时间
              examples:
                Example 1:
                  value:
                    id: '28522648801820918'
                    username: '123321'
                    nickname: 李小四
                    token: 28522648801320969.crdix0mnpac0.38141bcbc37cfbff98d470b0b969b6c8bc70ccd56d0b3105832673976342b48f
                    issued_at: '2023-03-30T05:30:01.497Z'
                    lasted_at: '2023-03-30T07:12:11.125Z'
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-user-info
      description: 获取用户自身 session 信息
  /user/passwd:
    patch:
      summary: 修改密码
      operationId: patch-user-passwd
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 用户模块
      description: |-
        - 该接口是用户修改自己的密码，不可以修改他人密码。

        - 仅 `本地用户` 才支持修改密码。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                original:
                  format: password
                  description: 原来的密码
                  type: string
                password:
                  type: string
                  format: password
                  minLength: 6
                  maxLength: 32
                  description: 新设置的密码
              required:
                - original
                - password
            examples:
              Example 1:
                value:
                  original: P@33w0rd
                  password: Az.0wsd8&
  /oplogs:
    get:
      summary: 查询用户操作日志
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-oplogs
      tags:
        - 用户日志
      description: 查询用户操作日志
      parameters:
        - $ref: '#/components/parameters/PageCurrent'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/filters'
        - $ref: '#/components/parameters/order'
        - $ref: '#/components/parameters/desc'
  '/brr/{broker}/{path}':
    parameters:
      - $ref: '#/components/parameters/broker_id_or_ip'
      - $ref: '#/components/parameters/path'
    get:
      summary: broker http
      tags:
        - 节点调用
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-brr-broker-path
      description: |
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    post:
      summary: broker http
      operationId: post-brr-broker-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    put:
      summary: broker http
      operationId: put-brr-broker-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
      tags:
        - 节点调用
    patch:
      summary: broker http
      operationId: patch-brr-broker-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
      tags:
        - 节点调用
    delete:
      summary: broker http
      operationId: delete-brr-broker-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
      tags:
        - 节点调用
    head:
      summary: broker http
      operationId: head-brr-broker-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
      tags:
        - 节点调用
  '/bws/{broker}/{path}':
    parameters:
      - $ref: '#/components/parameters/broker_id_or_ip'
      - $ref: '#/components/parameters/path'
    get:
      summary: broker websocket
      tags:
        - 节点调用
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-bws-broker-path
      description: |-
        `broker`：参数可以是 broker 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
  '/arr/{minion}/{path}':
    parameters:
      - $ref: '#/components/parameters/minion_id_or_ip'
      - $ref: '#/components/parameters/path'
    get:
      summary: minion(agent) http
      tags:
        - 节点调用
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-arr-minion-path
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    post:
      summary: minion(agent) http
      operationId: post-arr-minion-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    put:
      summary: minion(agent) http
      operationId: put-arr-minion-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    patch:
      summary: minion(agent) http
      operationId: patch-arr-minion-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    delete:
      summary: minion(agent) http
      operationId: delete-arr-minion-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
    head:
      summary: minion(agent) http
      operationId: head-arr-minion-path
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - 节点调用
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
  '/aws/{minion}/{path}':
    parameters:
      - $ref: '#/components/parameters/minion_id_or_ip'
      - $ref: '#/components/parameters/path'
    get:
      summary: minion(agent) websocket
      tags:
        - 节点调用
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-aws-minion-path
      description: |-
        `minion`：参数可以是 minion(agent) 节点的 IP 地址或 ID。

        `path`：路径和 broker 节点程序约定好。

        请求参数与响应参数根据接口来确定。
  /substances:
    get:
      summary: 插件分页查询
      tags:
        - 插件配置
      operationId: get-substances
      description: 插件分页查询
      parameters:
        - $ref: '#/components/parameters/PageCurrent'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Keyword'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: integer
                    description: 当前页码
                  size:
                    type: integer
                    description: 每页显示条数
                  total:
                    type: integer
                    description: 总条数
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 插件 ID
                        name:
                          type: string
                          description: 名字
                        icon:
                          type: string
                          description: 图标（Base64 编码）
                        desc:
                          type: string
                          description: 说明
                        created_at:
                          type: string
                          description: 创建时间
                        updated_at:
                          type: string
                          description: 更新时间
              examples:
                Example 1:
                  value:
                    current: 1
                    size: 10
                    total: 2
                    records:
                      - id: '28522653918371849'
                        name: seclog
                        icon: 5pel5b+X
                        desc: 日志回收
                        created_at: '2022-01-06T11:25:45+08:00'
                        updated_at: '2022-04-21T13:46:49+08:00'
                      - id: '71275045937627136'
                        name: linux_secure_logon
                        icon: bWFuZ2Vy
                        desc: centos 6 登录失败日志
                        created_at: '2022-08-16T16:21:35+08:00'
                        updated_at: '2022-09-27T11:20:50+08:00'
        '400':
          $ref: '#/components/responses/ProblemDetails'
  /substance/indices:
    get:
      summary: 配置 index
      tags:
        - 插件配置
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    data:
                      - id: '28522653918371841'
                        name: dnslog
                        icon: 6YCa55So
                        desc: dnslog服务平台
                        created_at: '2021-12-16T11:48:22+08:00'
                        updated_at: '2023-04-07T16:50:11+08:00'
                      - id: '57102750474190848'
                        name: dns_monitor_linux
                        icon: 6YCa55So
                        desc: linux平台dns监控
                        created_at: '2022-07-08T13:45:57+08:00'
                        updated_at: '2022-09-23T13:33:08+08:00'
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID
                        name:
                          type: string
                          description: 名字
                        icon:
                          type: string
                          description: 图标（Base64）
                        desc:
                          type: string
                          description: 说明
                        created_at:
                          type: string
                          description: 创建时间
                        updated_at:
                          type: string
                          description: 更新时间
              examples:
                Example 1:
                  value:
                    data:
                      - id: '28522653918371841'
                        name: dnslog
                        icon: 6YCa55So
                        desc: dnslog服务平台
                        created_at: '2021-12-16T11:48:22+08:00'
                        updated_at: '2023-04-07T16:50:11+08:00'
                      - id: '57102750474190848'
                        name: dns_monitor_linux
                        icon: 6YCa55So
                        desc: linux平台dns监控
                        created_at: '2022-07-08T13:45:57+08:00'
                        updated_at: '2022-09-23T13:33:08+08:00'
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-substance-indices
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Keyword'
      description: 配置 index
  /substance:
    get:
      summary: 查看插件配置详情
      tags:
        - 插件配置
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: '106329155535519744'
                    name: 测试一下下
                    icon: 6YCa55So
                    hash: 1de159548311ee4e12b679f8d4e1c864
                    desc: 嗡嗡嗡
                    chunk: cHJpbnQoMTIp
                    links: null
                    minion_id: '0'
                    version: 0
                    created_id: '28522648801320969'
                    updated_id: '28522648801320969'
                    created_at: '2022-11-21T09:54:06+08:00'
                    updated_at: '2022-11-21T09:54:06+08:00'
                properties:
                  id:
                    type: string
                    description: ID
                  name:
                    type: string
                    description: 名字
                  icon:
                    type: string
                    description: 图标（Base64）
                  hash:
                    type: string
                    description: 哈希
                  desc:
                    type: string
                    description: 说明
                  chunk:
                    type: string
                    description: 配置代理（Base64）
                  links:
                    type: array
                    description: 外链
                    deprecated: true
                    nullable: true
                    items:
                      type: string
                  minion_id:
                    type: string
                    description: 为 0 代表是共有配置，
                  version:
                    type: integer
                  created_id:
                    type: string
                    deprecated: true
                  updated_id:
                    type: string
                    deprecated: true
                  created_at:
                    type: string
                  updated_at:
                    type: string
              examples:
                Example 1:
                  value:
                    id: '106329155535519744'
                    name: 测试一下下
                    icon: 6YCa55So
                    hash: 1de159548311ee4e12b679f8d4e1c864
                    desc: 嗡嗡嗡
                    chunk: cHJpbnQoMTIp
                    links: null
                    minion_id: '0'
                    version: 0
                    created_id: '28522648801320969'
                    updated_id: '28522648801320969'
                    created_at: '2022-11-21T09:54:06+08:00'
                    updated_at: '2022-11-21T09:54:06+08:00'
        '400':
          $ref: '#/components/responses/ProblemDetails'
      operationId: get-substance
      parameters:
        - $ref: '#/components/parameters/ID'
      description: '`minion_id` 为 0 代表是公有配置。非 0 均为私有配置。'
  /alert-server:
    get:
      summary: 获取咚咚告警配置
      tags:
        - 配置参数
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  mode:
                    type: string
                    x-stoplight:
                      id: ujzp6wuu6uw5x
                    description: 发送模式
                    enum:
                      - siem
                      - dong
                    example: dong
                  name:
                    type: string
                    x-stoplight:
                      id: 7kgmiem5pdrr5
                    description: 名字
                    example: 安全应急响应中心
                  url:
                    type: string
                    x-stoplight:
                      id: 7ar432ot19mw4
                    description: 服务器地址
                    example: 'https://send.example.com'
                  token:
                    type: string
                    x-stoplight:
                      id: s1a19lv0vuvev
                    example: 6743dbc7a96dd591cf68375f
                    description: Token
                  account:
                    type: string
                    x-stoplight:
                      id: ccpf6jr0t45sa
                    example: '802563'
                    description: '`dong` 模式时有效'
                  created_at:
                    type: string
                    x-stoplight:
                      id: 0mm8dnlwk3bno
                    example: '2024-12-19T11:47:48.612Z'
                  updated_at:
                    type: string
                    x-stoplight:
                      id: wnpgjgl2teuna
                    example: '2024-12-19T11:47:48.612Z'
                required:
                  - mode
                  - name
                  - url
                  - token
      operationId: get-alert-server
      description: |-
        `mode`: 告警发送渠道

            - `dong`: 通过咚咚服务号发送。

            - `siem`: 通过 SIEM 平台发送。
    post:
      summary: 新增/修改咚咚告警配置
      operationId: post-alert-server
      responses:
        '200':
          description: OK
      tags:
        - 配置参数
      description: 新增/修改咚咚告警配置
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mode:
                  type: string
                  x-stoplight:
                    id: g5ffqt8q2l5eu
                  description: 发送模式
                  enum:
                    - siem
                    - dong
                  example: siem
                name:
                  type: string
                  x-stoplight:
                    id: n1np6koldikhz
                  description: 名字
                  example: 安全应急响应中心
                  minLength: 1
                  maxLength: 20
                url:
                  type: string
                  x-stoplight:
                    id: 6lkduo1ki4lfz
                  description: 服务器地址
                  example: 'https://send.example.com'
                token:
                  type: string
                  x-stoplight:
                    id: pp6phf060fhf2
                  description: Token
                  example: 6743dbc7a96dd591cf68375f
                account:
                  type: string
                  x-stoplight:
                    id: a1nlmunc4ppik
                  description: 账号，当为`dong`模式时必填。
                  example: '802568'
              required:
                - mode
                - name
                - url
                - token
    delete:
      summary: 删除咚咚告警配置
      operationId: delete-alert-server
      responses:
        '200':
          description: OK
      tags:
        - 配置参数
      description: 删除咚咚告警配置
  /siem-server:
    get:
      summary: 获取SIEM服务器连接参数
      tags:
        - 配置参数
      responses: {}
      operationId: get-siem-server
      description: 获取SIEM服务器连接参数
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: xcbvwvsd7q2v3
                  description: 名字
                  example: 测试名字
                url:
                  type: string
                  x-stoplight:
                    id: g448el60u6cwv
                  description: SIEM服务地址
                  example: 'https://siem.example.com'
                token:
                  type: string
                  x-stoplight:
                    id: kqt5pi6v9q19w
                  description: Token
                  example: secret.xxxxxx
                created_at:
                  type: string
                  x-stoplight:
                    id: 5hhnjxkrld1b5
                updated_at:
                  type: string
                  x-stoplight:
                    id: krchq037f6h3b
    post:
      summary: 新增/修改SIEM服务器连接参数
      operationId: post-siem-server
      responses:
        '200':
          description: OK
      tags:
        - 配置参数
      description: 新增/修改SIEM服务器连接参数
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: t76k68voj3uzs
                  example: 友好的名字
                  description: 名字
                url:
                  type: string
                  x-stoplight:
                    id: ytfvcjy9dxmez
                  description: 地址
                  example: 'https://siem.eastmoney.com'
                token:
                  type: string
                  x-stoplight:
                    id: uwuk0v8u8ck3k
                  description: Token
                  example: secret.xxxxxx
              required:
                - name
                - url
                - token
    delete:
      summary: 删除SIEM服务器连接参数
      operationId: delete-siem-server
      responses:
        '200':
          description: OK
      tags:
        - 配置参数
      description: 删除SIEM服务器连接参数
components:
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: 所有方法都可以将 Token 带到 Header 中
    authorization:
      name: authorization
      type: apiKey
      in: query
      description: 仅 `GET` 方法可以将 Token 带到查询参数中
  schemas: {}
  responses:
    ProblemDetails:
      description: 统一错误信息
      content:
        application/json:
          schema:
            type: object
            x-examples:
              Example 1:
                type: manager
                title: 请求错误
                status: 401
                detail: 认证无效
                instance: /api/v1/logout
            properties:
              type:
                type: string
                description: 报错节点类型
              title:
                type: string
                description: 错误标题
              status:
                type: integer
                description: 错误码，一般与 HTTP Status Code 一致
              detail:
                type: string
                description: 错误详情
              instance:
                type: string
                description: 请求 URI
          examples:
            Example 1:
              value:
                type: manager
                title: 参数校验错误
                status: 401
                detail: xxx 必须是邮箱
                instance: /api/v1/logout
  parameters:
    PageCurrent:
      name: current
      in: query
      required: true
      schema:
        type: integer
        example: 1
        minimum: 0
        default: 1
      description: 页码
    PageSize:
      name: size
      in: query
      required: true
      schema:
        type: integer
        example: 10
        minimum: 0
        maximum: 200
        default: 3
      description: 页码显示条数
    UserID:
      name: id
      in: query
      required: true
      schema:
        type: string
        minimum: 1
        example: '28522648801320969'
        maxLength: 20
        minLength: 1
        pattern: '^[0-9]+'
      description: 用户 ID
    ID:
      name: id
      in: query
      required: true
      schema:
        type: string
      description: ID
    broker_id_or_ip:
      name: broker
      in: path
      required: true
      schema:
        type: string
      description: broker 节点的 ID 或 IP
    path:
      name: path
      in: path
      required: true
      schema:
        type: string
      description: 路径
    minion_id_or_ip:
      name: minion
      in: path
      required: true
      schema:
        type: string
      description: minion (agent) 节点的 ID 或 IP
    Keyword:
      name: keyword
      in: query
      required: false
      schema:
        type: string
        maxLength: 100
      description: 搜索关键字
    filters:
      name: filters
      in: query
      required: false
      schema:
        example: '{"col":"name","op":"like","val":"tom"}'
        type: string
      description: 过滤条件
    order:
      name: order
      in: query
      required: false
      schema:
        type: string
      description: 排序条件
    desc:
      name: desc
      in: query
      required: false
      schema:
        type: boolean
      description: 是否倒序，结合 order 使用
  requestBodies: {}
security:
  - Authorization: []
